source 'http://rubygems.org'

gem 'thin'
gem 'rails', '3.2.8'
gem 'jquery-rails'
gem 'mongoid', '~> 3.0.0'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'bson_ext'
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'paperclip'